[project]
name = "Gradia"
version = "1.2.0"
requires-python = ">=3.9"

[tool.pyright]
venvPath = "."
venv = "venv"
reportAttributeAccessIssue = false  # Attributes aren't available for Gtk.TemplateChild objects
reportMissingModuleSource = false
